apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mysql_data"
