apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    type: localpvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
