apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecrets
  namespace: stack1 
type: kubernetes.io/basic-auth
stringData:
apiVersion: v1
kind: Secret
metadata:
  name: mysqlsecrets
  namespace: stack1
type: kubernetes.io/basic-auth
stringData:
  username: root         # MySQL username
  password: mypw         # MySQL root password
#this is the screts file for storing the ENV variables for mysql database, change the secret to to "Opaque" to be configured diffrently.
